apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wc88a7zrb-go 
  janus-idp.io/tekton: wc88a7zrb-go
  backstage.io/kubernetes-id: wc88a7zrb-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wc88a7zrb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml